### ISSUE TITLE
 The errors when run RBF and PDEs examples from Aboria guidance

### ISSUE THREAD

**Issue by adilijiang** [martinjrobins/Aboria#19] opened 2017-12-12 06:36 UTC
Hi, martin

I also copied the  RBF and PDEs model code from Aboria guidance to update source file getting_started.cpp(in attachment file PDEs_example.zip and RBF_example.zip), then execute the cmake. and make command to compile these two examples, but errors are generated after the compilation. How to solve this problem?

[PDEs_example.zip](https://github.com/martinjrobins/Aboria/files/1550494/PDEs_example.zip)
[RBF_example.zip](https://github.com/martinjrobins/Aboria/files/1550499/RBF_example.zip)

thanks again!
adilijiang

**Comment by martinjrobins** [comment] 2017-12-12 07:02
Hi @adilijiang. This was the same problem as the other examples (see #18). This should be fixed in the source now, it will take a few hours to appear on the website example.

**Comment by martinjrobins** [comment] 2017-12-12 07:11
email from @adilijiang:
```
yes,I have tried but it still have errors when I delete the ',std::vector,SearchMethod' and run it again.

typedef Particles<std::tuple<alpha,constant2,interpolated>,2,std::vector,SearchMethod> ParticlesType;
typedef Particles<std::tuple<alpha,constant2,interpolated>,2> ParticlesType;
```

**Comment by martinjrobins** [comment] 2017-12-12 07:17
What where the errors that you get? Were they related to not including Eigen? Note that you will need to modify the `CMakeLists.txt` given in the getting started section, in order to properly include Eigen. You will need to include something like:

```
find_package(Eigen3 REQUIRED)
add_definitions(-DHAVE_EIGEN)
list(APPEND INCLUDES ${EIGEN3_INCLUDE_DIR} )
 ```

**Comment by adilijiang** [comment] 2017-12-14 02:02
Thanks, Martin.
I updated the CMakeLists.txt and Annotated the TS_ASSERT lines even the for functions include the TS_ASSERT lines, it still doesn't work.
In addition, I would like to ask, do you still have an impression on how to use your previous year's project SPH-DEM? I'd like to try this project.

adilijiang

**Comment by martinjrobins** [comment] 2017-12-21 14:30
Can you attach your source code and the error message you are getting, then I can see what the problem is.

You are free to try and use SPH-DEM, but this code is abandoned at the moment, so won't receive any more updates, at least from me.

**Closed** 2018-05-14 12:02 UTC
