### ISSUE TITLE
The errors when run sph example from Aboria guidance

### ISSUE THREAD

**Issue by adilijiang** [martinjrobins/Aboria#18] opened 2017-12-12 04:49 UTC
Hi, martin

I copied the SPH model code from Aboria guidance to update source file getting_started.cpp(in attachment.zip), then execute the cmake. and make command to compile SPH example, but errors are generated after the compilation. How to solve this problem?

thanks! 
adilijiang

[attachment.zip](https://github.com/martinjrobins/Aboria/files/1550300/attachment.zip)

**Comment by martinjrobins** [comment] 2017-12-12 05:22
Thanks @adilijiang for filing an issue on this. The problem is this line in the source:

```
typedef Particles<std::tuple<kernel_radius,velocity,velocity_tmp,varh_omega,density,total_force,is_fixed,pressure_div_density2>,3,std::vector,SearchMethod> sph_type;
```

`SearchMethod` is not defined previously (although it is the automated tests!). This has been fixed in the example and should read:

```
typedef Particles<std::tuple<kernel_radius,velocity,velocity_tmp,varh_omega,density,total_force,is_fixed,pressure_div_density2>,3> sph_type;
```

**Comment by adilijiang** [comment] 2017-12-12 06:28
Yes, I tried again and it works now.Thank you~

**Comment by martinjrobins** [comment] 2017-12-12 06:28
Great, thanks again for reporting the bug.

**Closed by martinjrobins** 2017-12-12 06:28 UTC
